### PR TITLE
Create rock_paper_scissors.py

### PR DESCRIPTION
**Pull request by JackTDC**

### CODE REVIEW

**Review by coderAbhii — CHANGES_REQUESTED** [review]
In the program there is no option to exit the game.
I suggest you to make the necessary change.
The game is cool.. Just require the required changes.

**Good Luck!!**

**Comment by JackTDC** [comment]
Hey @coderAbhii I added an option to exit the game :)

**Review by coderAbhii — APPROVED** [review]
**Good Work!!** @JackTDC

**Comment by JackTDC** [comment]
Hey @coderAbhii When are you gonna merge it I need one more PR accepted to complete Hacktobefest

**Comment by coderAbhii** [comment]
> Hey @coderAbhii When are you gonna merge it I need one more PR accepted to complete Hacktobefest 

Sorry @JackTDC but it's not me who has the access to merge your pull request or mark it as 'hacktober-accepted'.

Please ask the owner of repository to do so.

**Pull request merged**
